spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: spring-ai-bootcamp-basic
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4.1-nano
          temperature: 0.1
      embedding:
        options:
          model: text-embedding-3-small

cors:
  allowed-origins: 'http://localhost:8080'

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
